<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;

use App\Models\District;
use App\Models\Region;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // \App\Models\User::factory(10)->create();

        // \App\Models\User::factory()->create([
        //     'name' => 'Test User',
        //     'email' => 'test@example.com',
        // ]);

        \App\Models\User::create([
            'name' => 'admin',
            'email' => 'admin@gmail.com',
            'password' => Hash::make('159753')
        ]);

        $dates = [
            ['id' => 2, 'name_uz' => 'Andijon viloyati', 'name_oz' => 'Андижон вилояти', 'name_ru' => 'Андижанская область'],
            ['id' => 3, 'name_uz' => 'Buxoro viloyati', 'name_oz' => 'Бухоро вилояти', 'name_ru' => 'Бухарская область'],
            ['id' => 4, 'name_uz' => 'Jizzax viloyati', 'name_oz' => 'Жиззах вилояти', 'name_ru' => 'Джизакская область'],
            ['id' => 5, 'name_uz' => 'Qashqadaryo viloyati', 'name_oz' => 'Қашқадарё вилояти', 'name_ru' => 'Кашкадарьинская область'],
            ['id' => 6, 'name_uz' => 'Navoiy viloyati', 'name_oz' => 'Навоий вилояти', 'name_ru' => 'Навоийская область'],
            ['id' => 7, 'name_uz' => 'Namangan viloyati', 'name_oz' => 'Наманган вилояти', 'name_ru' => 'Наманганская область'],
            ['id' => 8, 'name_uz' => 'Samarqand viloyati', 'name_oz' => 'Самарқанд вилояти', 'name_ru' => 'Самаркандская область'],
            ['id' => 10, 'name_uz' => 'Sirdaryo viloyati', 'name_oz' => 'Сирдарё вилояти', 'name_ru' => 'Сырдарьинская область'],
            ['id' => 11, 'name_uz' => 'Toshkent shahri', 'name_oz' => 'Тошкент шаҳри', 'name_ru' => 'город Ташкент'],
            ['id' => 12, 'name_uz' => 'Toshkent viloyati', 'name_oz' => 'Тошкент вилояти', 'name_ru' => 'Ташкентская область'],
            ['id' => 13, 'name_uz' => 'Farg\'ona viloyati', 'name_oz' => 'Фарғона вилояти', 'name_ru' => 'Ферганская область'],
            ['id' => 14, 'name_uz' => 'Xorazm viloyati', 'name_oz' => 'Хоразм вилояти', 'name_ru' => 'Хорезмская область'],
            ['id' => 15, 'name_uz' => 'Qoraqalpog\'iston Respublikasi', 'name_oz' => 'Қорақалпоғистон Республикаси', 'name_ru' => 'Республика Каракалпакстан'],
            ['id' => 5723, 'name_uz' => 'Surxondaryo viloyati', 'name_oz' => 'Сурхондарё вилояти', 'name_ru' => 'Сурхандарьинская область'],
        ];
        foreach ($dates as $item) {
            Region::create($item);    
        }

        $dates = [
            [
                'region_id' => 2,
                'name_uz' => 'Oltinko\'l tumani',
                'name_oz' => 'Олтинкўл тумани',
                'name_ru' => 'Алтынкульский район',
            ],
            [
                'region_id' => 2,
                'name_uz' => 'Andijon tumani',
                'name_oz' => 'Андижон тумани',
                'name_ru' => 'Андижанский район',
            ],
            [
                'region_id' => 2,
                'name_uz' => 'Baliqchi tumani',
                'name_oz' => 'Балиқчи тумани',
                'name_ru' => 'Балыкчинский район',
            ],
            [
                'region_id' => 2,
                'name_uz' => 'Bo\'z tumani',
                'name_oz' => 'Бўз тумани',
                'name_ru' => 'Бозский район',
            ],
            [
                'region_id' => 2,
                'name_uz' => 'Buloqboshi tumani',
                'name_oz' => 'Булоқбоши тумани',
                'name_ru' => 'Булакбашинский район',
            ],
            [
                'region_id' => 2,
                'name_uz' => 'Jalaquduq tumani',
                'name_oz' => 'Жалақудуқ тумани',
                'name_ru' => 'Джалалкудукский район',
            ],
            [
                'region_id' => 2,
                'name_uz' => 'Izboskan tumani',
                'name_oz' => 'Избоскан тумани',
                'name_ru' => 'Избасканский район',
            ],
            [
                'region_id' => 2,
                'name_uz' => 'Ulug\'nor tumani',
                'name_oz' => 'Улуғнор тумани',
                'name_ru' => 'Улугнорский район',
            ],
            [
                'region_id' => 2,
                'name_uz' => 'Qo\'rg\'ontepa tumani',
                'name_oz' => 'Қўрғонтепа тумани',
                'name_ru' => 'Кургантепинский район',
            ],
            [
                'region_id' => 2,
                'name_uz' => 'Asaka tumani',
                'name_oz' => 'Асака тумани',
                'name_ru' => 'Асакинский район',
            ],
            [
                'region_id' => 2,
                'name_uz' => 'Marxamat tumani',
                'name_oz' => 'Мархамат тумани',
                'name_ru' => 'Мархаматский район',
            ],
            [
                'region_id' => 2,
                'name_uz' => 'Shahrixon tumani',
                'name_oz' => 'Шаҳрихон тумани',
                'name_ru' => 'Шахриханский район',
            ],
            [
                'region_id' => 2,
                'name_uz' => 'Paxtaobod tumani',
                'name_oz' => 'Пахтаобод тумани',
                'name_ru' => 'Пахтаабадский район',
            ],
            [
                'region_id' => 2,
                'name_uz' => 'Xo\'jaobod tumani',
                'name_oz' => 'Хўжаобод тумани',
                'name_ru' => 'Ходжаабадский район',
            ],
            [
                'region_id' => 2,
                'name_uz' => 'Andijon',
                'name_oz' => 'Андижон',
                'name_ru' => 'Андижан',
            ],
            [
                'region_id' => 2,
                'name_uz' => 'Xonobod',
                'name_oz' => 'Хонобод',
                'name_ru' => 'Ханабад',
            ],
            [
                'region_id' => 3,
                'name_uz' => 'Olot tumani',           
                'name_oz' => 'Олот тумани',
                'name_ru' => 'Алатский район',
            ],
            [
                'region_id' => 3,
                'name_uz' => 'Buxoro tumani',
                'name_oz' => 'Бухоро тумани',
                'name_ru' => 'Бухарский район',
            ],
            [
                'region_id' => 3,
                'name_uz' => 'Vobkent tumani',
                'name_oz' => 'Вобкент тумани',
                'name_ru' => 'Вабкентский район',
            ],
            [
                'region_id' => 3,
                'name_uz' => 'G\'ijduvon tumani',
                'name_oz' => 'Ғиждувон тумани',
                'name_ru' => 'Гиждуванский район',
            ],
            [
                'region_id' => 3,
                'name_uz' => 'Kogon tumani',
                'name_oz' => 'Когон тумани',
                'name_ru' => 'Каганский район',
            ],
            [
                'region_id' => 3,
                'name_uz' => 'Qorako\'l tumani',
                'name_oz' => 'Қоракўл тумани',
                'name_ru' => 'Каракульский район',
            ],
            [
                'region_id' => 3,
                'name_uz' => 'Qorovulbozor tumani',
                'name_oz' => 'Қоровулбозор тумани',
                'name_ru' => 'Караулбазарский район',
            ],
            [
                'region_id' => 3,
                'name_uz' => 'Peshku tumani',
                'name_oz' => 'Пешку тумани',
                'name_ru' => 'Пешкунский район',
            ],
            [
                'region_id' => 3,
                'name_uz' => 'Romitan tumani',
                'name_oz' => 'Ромитан тумани',
                'name_ru' => 'Ромитанский район',
            ],
            [
                'region_id' => 3,
                'name_uz' => 'Jondor tumani',
                'name_oz' => 'Жондор тумани',
                'name_ru' => 'Жандарский район',
            ],
            [
                'region_id' => 3,
                'name_uz' => 'Shofirkon tumani',
                'name_oz' => 'Шофиркон тумани',
                'name_ru' => 'Шафирканский район',
            ],
            [
                'region_id' => 3,
                'name_uz' => 'Buxoro',
                'name_oz' => 'Бухоро',
                'name_ru' => 'Бухара',
            ],
            [
                'region_id' => 3,
                'name_uz' => 'Kogon',
                'name_oz' => 'Когон',
                'name_ru' => 'Каган',
            ],
            [
                'region_id' => 4,
                'name_uz' => 'Arnasoy tumani',
                'name_oz' => 'Арнасой тумани',
                'name_ru' => 'Арнасайский район',
            ],
            [
                'region_id' => 4,
                'name_uz' => 'Baxmal tumani',
                'name_oz' => 'Бахмал тумани',
                'name_ru' => 'Бахмальский район',
            ],
            [
                'region_id' => 4,
                'name_uz' => 'G\'allaorol tumani',
                'name_oz' => 'Ғаллаорол тумани',
                'name_ru' => 'Галляаральский район',
            ],
            [
                'region_id' => 4,
                'name_uz' => 'Do\'stlik tumani',
                'name_oz' => 'Дўстлик тумани',
                'name_ru' => 'Дустликский район',
            ],
            [
                'region_id' => 4,
                'name_uz' => 'Zomin tumani',
                'name_oz' => 'Зомин тумани',
                'name_ru' => 'Зааминский район',
            ],
            [
                'region_id' => 4,
                'name_uz' => 'Zarbdor tumani',
                'name_oz' => 'Зарбдор тумани',
                'name_ru' => 'Зарбдарский район',
            ],
            [
                'region_id' => 4,
                'name_uz' => 'Mirzacho\'l tumani',
                'name_oz' => 'Мирзачўл тумани',
                'name_ru' => 'Мирзачульский район',
            ],
            [
                'region_id' => 4,
                'name_uz' => 'Zafarobod tumani',
                'name_oz' => 'Зафаробод тумани',
                'name_ru' => 'Зафарабадский район',
            ],
            [
                'region_id' => 4,
                'name_uz' => 'Paxtakor tumani',
                'name_oz' => 'Пахтакор тумани',
                'name_ru' => 'Пахтакорский район',
            ],
            [
                'region_id' => 4,
                'name_uz' => 'Forish tumani',
                'name_oz' => 'Фориш тумани',
                'name_ru' => 'Фаришский район',
            ],
            [
                'region_id' => 4,
                'name_uz' => 'Yangiobod tumani',
                'name_oz' => 'Янгиобод тумани',
                'name_ru' => 'Янгиабадский район',
            ],
            [
                'region_id' => 4,
                'name_uz' => 'Jizzax',
                'name_oz' => 'Жиззах',
                'name_ru' => 'Джизак',
            ],
            [
                'region_id' => 4,
                'name_uz' => 'Sh.Rashidov tumani',
                'name_oz' => 'Ш.Рашидов тумани',
                'name_ru' => 'Ш.Рашидовский район',
            ],
            [
                'region_id' => 5,
                'name_uz' => 'G\'uzor tumani',
                'name_oz' => 'Ғузор тумани',
                'name_ru' => 'Гузарский район',
            ],
            [
                'region_id' => 5,
                'name_uz' => 'Dehqonobod tumani',
                'name_oz' => 'Деҳқонобод тумани',
                'name_ru' => 'Дехканабадский район',
            ],
            [
                'region_id' => 5,
                'name_uz' => 'Qamashi tumani',
                'name_oz' => 'Қамаши тумани',
                'name_ru' => 'Камашинский район',
            ],
            [
                'region_id' => 5,
                'name_uz' => 'Qarshi tumani',
                'name_oz' => 'Қарши тумани',
                'name_ru' => 'Каршинский район',
            ],
            [
                'region_id' => 5,
                'name_uz' => 'Koson tumani',
                'name_oz' => 'Косон тумани',
                'name_ru' => 'Касанский район',
            ],
            [
                'region_id' => 5,
                'name_uz' => 'Kitob tumani',
                'name_oz' => 'Китоб тумани',
                'name_ru' => 'Китабский район',
            ],
            [
                'region_id' => 5,
                'name_uz' => 'Mirishkor tumani',
                'name_oz' => 'Миришкор тумани',
                'name_ru' => 'Миришкорский район',
            ],
            [
                'region_id' => 5,
                'name_uz' => 'Muborak tumani',
                'name_oz' => 'Муборак тумани',
                'name_ru' => 'Мубарекский район',
            ],
            [
                'region_id' => 5,
                'name_uz' => 'Nishon tumani',
                'name_oz' => 'Нишон тумани',
                'name_ru' => 'Нишанский район',
            ],
            [
                'region_id' => 5,
                'name_uz' => 'Kasbi tumani',
                'name_oz' => 'Касби тумани',
                'name_ru' => 'Касбинский район',
            ],
            [
                'region_id' => 5,
                'name_uz' => 'Chiroqchi tumani',
                'name_oz' => 'Чироқчи тумани',
                'name_ru' => 'Чиракчинский район',
            ],
            [
                'region_id' => 5,
                'name_uz' => 'Shahrisabz tumani',
                'name_oz' => 'Шаҳрисабз тумани',
                'name_ru' => 'Шахрисабзский район',
            ],
            [
                'region_id' => 5,
                'name_uz' => 'Yakkabog\' tumani',
                'name_oz' => 'Яккабоғ тумани',
                'name_ru' => 'Яккабагский район',
            ],
            [
                'region_id' => 5,
                'name_uz' => 'Qarshi',
                'name_oz' => 'Қарши',
                'name_ru' => 'Карши',
            ],
            [
                'region_id' => 5,
                'name_uz' => 'Shahrisabz',
                'name_oz' => 'Шаҳрисабз',
                'name_ru' => 'Шахрисабз',
            ],
            [
                'region_id' => 5,
                'name_uz' => 'Ko‘kdala tumani',
                'name_oz' => 'Кўкдала тумани',
                'name_ru' => 'Кукдалинский район',
            ],
            [
                'region_id' => 6,
                'name_uz' => 'Konimex tumani',
                'name_oz' => 'Конимех тумани',
                'name_ru' => 'Канимехский район',
            ],
            [
                'region_id' => 6,
                'name_uz' => 'Qiziltepa tumani',
                'name_oz' => 'Қизилтепа тумани',
                'name_ru' => 'Кызылтепинский район',
            ],
            [
                'region_id' => 6,
                'name_uz' => 'Navbahor tumani',
                'name_oz' => 'Навбаҳор тумани',
                'name_ru' => 'Навбахорский район',
            ],
            [
                'region_id' => 6,
                'name_uz' => 'Karmana tumani',
                'name_oz' => 'Кармана тумани',
                'name_ru' => 'Карманинский район',
            ],
            [
                'region_id' => 6,
                'name_uz' => 'Nurota tumani',
                'name_oz' => 'Нурота тумани',
                'name_ru' => 'Нуратинский район',
            ],
            [
                'region_id' => 6,
                'name_uz' => 'Tomdi tumani',
                'name_oz' => 'Томди тумани',
                'name_ru' => 'Тамдынский район',
            ],
            [
                'region_id' => 6,
                'name_uz' => 'Uchquduq tumani',
                'name_oz' => 'Учқудуқ тумани',
                'name_ru' => 'Учкудукский район',
            ],
            [
                'region_id' => 6,
                'name_uz' => 'Xatirchi tumani',
                'name_oz' => 'Хатирчи тумани',
                'name_ru' => 'Хатырчинский район',
            ],
            [
                'region_id' => 6,
                'name_uz' => 'Navoiy',
                'name_oz' => 'Навоий',
                'name_ru' => 'Навои',
            ],
            [
                'region_id' => 6,
                'name_uz' => 'Zarafshon',
                'name_oz' => 'Зарафшон',
                'name_ru' => 'Зарафшан',
            ],
            [
                'region_id' => 6,
                'name_uz' => 'G‘ozg‘on tumani',
                'name_oz' => 'Ғозғон тумани',
                'name_ru' => 'Газганский район',
            ],
            [
                'region_id' => 7,
                'name_uz' => 'Mingbuloq tumani',
                'name_oz' => 'Мингбулоқ тумани',
                'name_ru' => 'Мингбулакский район',
            ],
            [
                'region_id' => 7,
                'name_uz' => 'Kosonsoy tumani',
                'name_oz' => 'Косонсой тумани',
                'name_ru' => 'Касансайский район',
            ],
            [
                'region_id' => 7,
                'name_uz' => 'Namangan tumani',
                'name_oz' => 'Наманган тумани',
                'name_ru' => 'Наманганский район',
            ],
            [
                'region_id' => 7,
                'name_uz' => 'Norin tumani',
                'name_oz' => 'Норин тумани',
                'name_ru' => 'Нарынский район',
            ],
            [
                'region_id' => 7,
                'name_uz' => 'Pop tumani',
                'name_oz' => 'Поп тумани',
                'name_ru' => 'Папский район',
            ],
            [
                'region_id' => 7,
                'name_uz' => 'To\'raqo\'rg\'on tumani',
                'name_oz' => 'Тўрақўрғон тумани',
                'name_ru' => 'Туракурганский район',
            ],
            [
                'region_id' => 7,
                'name_uz' => 'Uychi tumani',
                'name_oz' => 'Уйчи тумани',
                'name_ru' => 'Уйчинский район',
            ],
            [
                'region_id' => 7,
                'name_uz' => 'Uchqo\'rg\'on tumani',
                'name_oz' => 'Учқўрғон тумани',
                'name_ru' => 'Учкурганский район',
            ],
            [
                'region_id' => 7,
                'name_uz' => 'Chortoq tumani',
                'name_oz' => 'Чортоқ тумани',
                'name_ru' => 'Чартакский район',
            ],
            [
                'region_id' => 7,
                'name_uz' => 'Chust tumani',
                'name_oz' => 'Чуст тумани',
                'name_ru' => 'Чустский район',
            ],
            [
                'region_id' => 7,
                'name_uz' => 'Yangiqo\'rg\'on tumani',
                'name_oz' => 'Янгиқўрғон тумани',
                'name_ru' => 'Янгикурганский район',
            ],
            [
                'region_id' => 7,
                'name_uz' => 'Namangan',
                'name_oz' => 'Наманган',
                'name_ru' => 'Наманган',
            ],
            [
                'region_id' => 7,
                'name_uz' => 'Davlatobod tumani',
                'name_oz' => 'Давлатобод тумани',
                'name_ru' => 'Давлатабадский район',
            ],
            [
                'region_id' => 7,
                'name_uz' => 'Yangi Namangan tumani',
                'name_oz' => 'Янги Наманган тумани',
                'name_ru' => 'Янги Наманганский район',
            ],
            [
                'region_id' => 8,
                'name_uz' => 'Oqdaryo tumani',
                'name_oz' => 'Оқдарё тумани',
                'name_ru' => 'Акдарьинский район',
            ],
            [
                'region_id' => 8,
                'name_uz' => 'Bulung\'ur tumani',
                'name_oz' => 'Булунғур тумани',
                'name_ru' => 'Булунгурский район',
            ],
            [
                'region_id' => 8,
                'name_uz' => 'Jomboy tumani',
                'name_oz' => 'Жомбой тумани',
                'name_ru' => 'Джамбайский район',
            ],
            [
                'region_id' => 8,
                'name_uz' => 'Ishtixon tumani',
                'name_oz' => 'Иштихон тумани',
                'name_ru' => 'Иштыханский район',
            ],
            [
                'region_id' => 8,
                'name_uz' => 'Kattaqo\'rg\'on tumani',
                'name_oz' => 'Каттақўрғон тумани',
                'name_ru' => 'Каттакурганский район',
            ],
            [
                'region_id' => 8,
                'name_uz' => 'Qo\'shrabot tumani',
                'name_oz' => 'Қўшработ тумани',
                'name_ru' => 'Кушрабадский район',
            ],
            [
                'region_id' => 8,
                'name_uz' => 'Narpay tumani',
                'name_oz' => 'Нарпай тумани',
                'name_ru' => 'Нарпайский район',
            ],
            [
                'region_id' => 8,
                'name_uz' => 'Payariq tumani',
                'name_oz' => 'Паяриқ тумани',
                'name_ru' => 'Пайарыкский район',
            ],
            [
                'region_id' => 8,
                'name_uz' => 'Pastdarg\'om tumani',
                'name_oz' => 'Пастдарғом тумани',
                'name_ru' => 'Пастдаргомский район',
            ],
            [
                'region_id' => 8,
                'name_uz' => 'Paxtachi tumani',
                'name_oz' => 'Пахтачи тумани',
                'name_ru' => 'Пахтачийский район',
            ],
            [
                'region_id' => 8,
                'name_uz' => 'Samarqand tumani',
                'name_oz' => 'Самарқанд тумани',
                'name_ru' => 'Самаркандский район',
            ],
            [
                'region_id' => 8,
                'name_uz' => 'Nurobod tumani',
                'name_oz' => 'Нуробод тумани',
                'name_ru' => 'Нурабадский район',
            ],
            [
                'region_id' => 8,
                'name_uz' => 'Urgut tumani',
                'name_oz' => 'Ургут тумани',
                'name_ru' => 'Ургутский район',
            ],
            [
                'region_id' => 8,
                'name_uz' => 'Tayloq tumani',
                'name_oz' => 'Тайлоқ тумани',
                'name_ru' => 'Тайлякский район',
            ],
            [
                'region_id' => 8,
                'name_uz' => 'Samarqand',
                'name_oz' => 'Самарқанд',
                'name_ru' => 'Самарканд',
            ],
            [
                'region_id' => 8,
                'name_uz' => 'Kattaqo\'rg\'on',
                'name_oz' => 'Каттақўрғон',
                'name_ru' => 'Каттакурган',
            ],
            [
                'region_id' => 5723,
                'name_uz' => 'Oltinsoy tumani',
                'name_oz' => 'Олтинсой тумани',
                'name_ru' => 'Алтынсайский район',
            ],
            [
                'region_id' => 5723,
                'name_uz' => 'Angor tumani',
                'name_oz' => 'Ангор тумани',
                'name_ru' => 'Ангорский район',
            ],
            [
                'region_id' => 5723,
                'name_uz' => 'Boysun tumani',
                'name_oz' => 'Бойсун тумани',
                'name_ru' => 'Байсунский район',
            ],
            [
                'region_id' => 5723,
                'name_uz' => 'Muzrabot tumani',
                'name_oz' => 'Музработ тумани',
                'name_ru' => 'Музрабадский район',
            ],
            [
                'region_id' => 5723,
                'name_uz' => 'Denov tumani',
                'name_oz' => 'Денов тумани',
                'name_ru' => 'Денауский район',
            ],
            [
                'region_id' => 5723,
                'name_uz' => 'Jarqo\'rg\'on tumani',
                'name_oz' => 'Жарқўрғон тумани',
                'name_ru' => 'Джаркурганский район',
            ],
            [
                'region_id' => 5723,
                'name_uz' => 'Qumqo\'rg\'on tumani',
                'name_oz' => 'Қумқўрғон тумани',
                'name_ru' => 'Кумкурганский район',
            ],
            [
                'region_id' => 5723,
                'name_uz' => 'Qiziriq tumani',
                'name_oz' => 'Қизириқ тумани',
                'name_ru' => 'Кизирикский район',
            ],
            [
                'region_id' => 5723,
                'name_uz' => 'Sariosiyo tumani',
                'name_oz' => 'Сариосиё тумани',
                'name_ru' => 'Сариасийский район',
            ],
            [
                'region_id' => 5723,
                'name_uz' => 'Termiz tumani',
                'name_oz' => 'Термиз тумани',
                'name_ru' => 'Термезский район',
            ],
            [
                'region_id' => 5723,
                'name_uz' => 'Uzun tumani',
                'name_oz' => 'Узун тумани',
                'name_ru' => 'Узунский район',
            ],
            [
                'region_id' => 5723,
                'name_uz' => 'Sherobod tumani',
                'name_oz' => 'Шеробод тумани',
                'name_ru' => 'Шерабадский район',
            ],
            [
                'region_id' => 5723,
                'name_uz' => 'Sho\'rchi tumani',
                'name_oz' => 'Шўрчи тумани',
                'name_ru' => 'Шурчинский район',
            ],
            [
                'region_id' => 5723,
                'name_uz' => 'Termiz',
                'name_oz' => 'Термиз',
                'name_ru' => 'Термез',
            ],
            [
                'region_id' => 5723,
                'name_uz' => 'Bandixon tumani',
                'name_oz' => 'Бандихон тумани',
                'name_ru' => 'Бандиханский район',
            ],
            [
                'region_id' => 10,
                'name_uz' => 'Oqoltin tumani',
                'name_oz' => 'Оқолтин тумани',
                'name_ru' => 'Акалтынский район',
            ],
            [
                'region_id' => 10,
                'name_uz' => 'Boyovut tumani',
                'name_oz' => 'Боёвут тумани',
                'name_ru' => 'Баяутский район',
            ],
            [
                'region_id' => 10,
                'name_uz' => 'Sayxunobod tumani',
                'name_oz' => 'Сайхунобод тумани',
                'name_ru' => 'Сайхунабадский район',
            ],
            [
                'region_id' => 10,
                'name_uz' => 'Guliston tumani',
                'name_oz' => 'Гулистон тумани',
                'name_ru' => 'Гулистанский район',
            ],
            [
                'region_id' => 10,
                'name_uz' => 'Sardoba tumani',
                'name_oz' => 'Сардоба тумани',
                'name_ru' => 'Сардобинский район',
            ],
            [
                'region_id' => 10,
                'name_uz' => 'Mirzaobod tumani',
                'name_oz' => 'Мирзаобод тумани',
                'name_ru' => 'Мирзаабадский район',
            ],
            [
                'region_id' => 10,
                'name_uz' => 'Sirdaryo tumani',
                'name_oz' => 'Сирдарё тумани',
                'name_ru' => 'Сырдарьинский район',
            ],
            [
                'region_id' => 10,
                'name_uz' => 'Xovos tumani',
                'name_oz' => 'Ховос тумани',
                'name_ru' => 'Хавастский район',
            ],
            [
                'region_id' => 10,
                'name_uz' => 'Guliston',
                'name_oz' => 'Гулистон',
                'name_ru' => 'Гулистан',
            ],
            [
                'region_id' => 10,
                'name_uz' => 'Shirin',
                'name_oz' => 'Ширин',
                'name_ru' => 'Ширин',
            ],
            [
                'region_id' => 10,
                'name_uz' => 'Yangiyer',
                'name_oz' => 'Янгиер',
                'name_ru' => 'Янгиер',
            ],
            [
                'region_id' => 10,
                'name_uz' => 'Baxt shaxar',
                'name_oz' => 'Бахт шахар',
                'name_ru' => 'город Бахт',
            ],
            [
                'region_id' => 11,
                'name_uz' => 'Uchtepa tumani',
                'name_oz' => 'Учтепа тумани',
                'name_ru' => 'Учтепинский район',
            ],
            [
                'region_id' => 11,
                'name_uz' => 'Bektemir tumani',
                'name_oz' => 'Бектемир тумани',
                'name_ru' => 'Бектемирский район',
            ],
            [
                'region_id' => 11,
                'name_uz' => 'Yunusobod tumani',
                'name_oz' => 'Юнусобод тумани',
                'name_ru' => 'Юнусабадский район',
            ],
            [
                'region_id' => 11,
                'name_uz' => 'Mirzo Ulug\'bek tumani',
                'name_oz' => 'Мирзо Улуғбек тумани',
                'name_ru' => 'Мирзо-Улугбекский район',
            ],
            [
                'region_id' => 11,
                'name_uz' => 'Mirobod tumani',
                'name_oz' => 'Миробод тумани',
                'name_ru' => 'Мирабадский район',
            ],
            [
                'region_id' => 11,
                'name_uz' => 'Shayxontohur tumani',
                'name_oz' => 'Шайхонтоҳур тумани',
                'name_ru' => 'Шайхантахурский район',
            ],
            [
                'region_id' => 11,
                'name_uz' => 'Olmazor tumani',
                'name_oz' => 'Олмазор тумани',
                'name_ru' => 'Алмазарский район',
            ],
            [
                'region_id' => 11,
                'name_uz' => 'Sirg\'ali tumani',
                'name_oz' => 'Сирғали тумани',
                'name_ru' => 'Сергелийский район',
            ],
            [
                'region_id' => 11,
                'name_uz' => 'Yakkasaroy tumani',
                'name_oz' => 'Яккасарой тумани',
                'name_ru' => 'Яккасарайский район',
            ],
            [
                'region_id' => 11,
                'name_uz' => 'Yashnobod tumani',
                'name_oz' => 'Яшнобод тумани',
                'name_ru' => 'Яшнабадский район',
            ],
            [
                'region_id' => 11,
                'name_uz' => 'Chilonzor tumani',
                'name_oz' => 'Чилонзор тумани',
                'name_ru' => 'Чиланзарский район',
            ],
            [
                'region_id' => 11,
                'name_uz' => 'Yangihayot tumani',
                'name_oz' => 'Янгиҳаёт тумани',
                'name_ru' => 'Янгихаётский район',
            ],
            [
                'region_id' => 12,
                'name_uz' => 'Oqqo\'rg\'on tumani',
                'name_oz' => 'Оққўрғон тумани',
                'name_ru' => 'Аккурганский район',
            ],
            [
                'region_id' => 12,
                'name_uz' => 'Ohangaron tumani',
                'name_oz' => 'Оҳангарон тумани',
                'name_ru' => 'Ахангаранский район',
            ],
            [
                'region_id' => 12,
                'name_uz' => 'Bekobod tumani',
                'name_oz' => 'Бекобод тумани',
                'name_ru' => 'Бекабадский район',
            ],
            [
                'region_id' => 12,
                'name_uz' => 'Bo\'stonliq tumani',
                'name_oz' => 'Бўстонлиқ тумани',
                'name_ru' => 'Бостанлыкский район',
            ],
            [
                'region_id' => 12,
                'name_uz' => 'Bo\'ka tumani',
                'name_oz' => 'Бўка тумани',
                'name_ru' => 'Букинский район',
            ],
            [
                'region_id' => 12,
                'name_uz' => 'Zangiota tumani',
                'name_oz' => 'Зангиота тумани',
                'name_ru' => 'Зангиатинский район',
            ],
            [
                'region_id' => 12,
                'name_uz' => 'Yuqorichirchiq tumani',
                'name_oz' => 'Юқоричирчиқ тумани',
                'name_ru' => 'Юкоричирчикский район',
            ],
            [
                'region_id' => 12,
                'name_uz' => 'Qibray tumani',
                'name_oz' => 'Қибрай тумани',
                'name_ru' => 'Кибрайский район',
            ],
            [
                'region_id' => 12,
                'name_uz' => 'Parkent tumani',
                'name_oz' => 'Паркент тумани',
                'name_ru' => 'Паркентский район',
            ],
            [
                'region_id' => 12,
                'name_uz' => 'Piskent tumani',
                'name_oz' => 'Пискент тумани',
                'name_ru' => 'Пскентский район',
            ],
            [
                'region_id' => 12,
                'name_uz' => 'O\'rtachirchiq tumani',
                'name_oz' => 'Ўртачирчиқ тумани',
                'name_ru' => 'Уртачирчикский район',
            ],
            [
                'region_id' => 12,
                'name_uz' => 'Chinoz tumani',
                'name_oz' => 'Чиноз тумани',
                'name_ru' => 'Чиназский район',
            ],
            [
                'region_id' => 12,
                'name_uz' => 'Yangiyo\'l tumani',
                'name_oz' => 'Янгийўл тумани',
                'name_ru' => 'Янгиюльский район',
            ],
            [
                'region_id' => 12,
                'name_uz' => 'Toshkent tumani',
                'name_oz' => 'Тошкент тумани',
                'name_ru' => 'Ташкентский район',
            ],
            [
                'region_id' => 12,
                'name_uz' => 'Quyichirchiq tumani',
                'name_oz' => 'Қуйичирчиқ тумани',
                'name_ru' => 'Куйичирчикский район',
            ],
            [
                'region_id' => 12,
                'name_uz' => 'Nurafshon',
                'name_oz' => 'Нурафшон',
                'name_ru' => 'Нурафшон',
            ],
            [
                'region_id' => 12,
                'name_uz' => 'Olmaliq',
                'name_oz' => 'Олмалиқ',
                'name_ru' => 'Алмалык',
            ],
            [
                'region_id' => 12,
                'name_uz' => 'Angren',
                'name_oz' => 'Ангрен',
                'name_ru' => 'Ангрен',
            ],
            [
                'region_id' => 12,
                'name_uz' => 'Bekobod',
                'name_oz' => 'Бекобод',
                'name_ru' => 'Бекабад',
            ],
            [
                'region_id' => 12,
                'name_uz' => 'Ohangaron',
                'name_oz' => 'Оҳангарон',
                'name_ru' => 'Ахангаран',
            ],
            [
                'region_id' => 12,
                'name_uz' => 'Chirchiq',
                'name_oz' => 'Чирчиқ',
                'name_ru' => 'Чирчик',
            ],
            [
                'region_id' => 12,
                'name_uz' => 'Yangiyo\'l',
                'name_oz' => 'Янгийўл',
                'name_ru' => 'Янгиюль',
            ],
            [
                'region_id' => 13,
                'name_uz' => 'Oltiariq tumani',
                'name_oz' => 'Олтиариқ тумани',
                'name_ru' => 'Алтыарыкский район',
            ],
            [
                'region_id' => 13,
                'name_uz' => 'Qo\'shtepa tumani',
                'name_oz' => 'Қўштепа тумани',
                'name_ru' => 'Куштепинский район',
            ],
            [
                'region_id' => 13,
                'name_uz' => 'Bog\'dod tumani',
                'name_oz' => 'Боғдод тумани',
                'name_ru' => 'Багдадский район',
            ],
            [
                'region_id' => 13,
                'name_uz' => 'Buvayda tumani',
                'name_oz' => 'Бувайда тумани',
                'name_ru' => 'Бувайдинский район',
            ],
            [
                'region_id' => 13,
                'name_uz' => 'Beshariq tumani',
                'name_oz' => 'Бешариқ тумани',
                'name_ru' => 'Бешарыкский район',
            ],
            [
                'region_id' => 13,
                'name_uz' => 'Quva tumani',
                'name_oz' => 'Қува тумани',
                'name_ru' => 'Кувинский район',
            ],
            [
                'region_id' => 13,
                'name_uz' => 'Uchko\'prik tumani',
                'name_oz' => 'Учкўприк тумани',
                'name_ru' => 'Учкуприкский район',
            ],
            [
                'region_id' => 13,
                'name_uz' => 'Rishton tumani',
                'name_oz' => 'Риштон тумани',
                'name_ru' => 'Риштанский район',
            ],
            [
                'region_id' => 13,
                'name_uz' => 'So\'x tumani',
                'name_oz' => 'Сўх тумани',
                'name_ru' => 'Сохский район',
            ],
            [
                'region_id' => 13,
                'name_uz' => 'Toshloq tumani',
                'name_oz' => 'Тошлоқ тумани',
                'name_ru' => 'Ташлакский район',
            ],
            [
                'region_id' => 13,
                'name_uz' => 'O\'zbekiston tumani',
                'name_oz' => 'Ўзбекистон тумани',
                'name_ru' => 'Узбекистанский район',
            ],
            [
                'region_id' => 13,
                'name_uz' => 'Farg\'ona tumani',
                'name_oz' => 'Фарғона тумани',
                'name_ru' => 'Ферганский район',
            ],
            [
                'region_id' => 13,
                'name_uz' => 'Dang\'ara tumani',
                'name_oz' => 'Данғара тумани',
                'name_ru' => 'Дангаринский район',
            ],
            [
                'region_id' => 13,
                'name_uz' => 'Furqat tumani',
                'name_oz' => 'Фурқат тумани',
                'name_ru' => 'Фуркатский район',
            ],
            [
                'region_id' => 13,
                'name_uz' => 'Yozyovon tumani',
                'name_oz' => 'Ёзёвон тумани',
                'name_ru' => 'Язъяванский район',
            ],
            [
                'region_id' => 13,
                'name_uz' => 'Farg\'ona',
                'name_oz' => 'Фарғона',
                'name_ru' => 'Фергана',
            ],
            [
                'region_id' => 13,
                'name_uz' => 'Qo\'qon',
                'name_oz' => 'Қўқон',
                'name_ru' => 'Коканд',
            ],
            [
                'region_id' => 13,
                'name_uz' => 'Quvasoy',
                'name_oz' => 'Қувасой',
                'name_ru' => 'Кувасай',
            ],
            [
                'region_id' => 13,
                'name_uz' => 'Marg\'ilon',
                'name_oz' => 'Марғилон',
                'name_ru' => 'Маргилан',
            ],
            [
                'region_id' => 14,
                'name_uz' => 'Bog\'ot tumani',
                'name_oz' => 'Боғот тумани',
                'name_ru' => 'Багатский район',
            ],
            [
                'region_id' => 14,
                'name_uz' => 'Gurlan tumani',
                'name_oz' => 'Гурлан тумани',
                'name_ru' => 'Гурленский район',
            ],
            [
                'region_id' => 14,
                'name_uz' => 'Qo\'shko\'pir tumani',
                'name_oz' => 'Қўшкўпир тумани',
                'name_ru' => 'Кошкупырский район',
            ],
            [
                'region_id' => 14,
                'name_uz' => 'Urganch tumani',
                'name_oz' => 'Урганч тумани',
                'name_ru' => 'Ургенчский район',
            ],
            [
                'region_id' => 14,
                'name_uz' => 'Xazorasp tumani',
                'name_oz' => 'Хазорасп тумани',
                'name_ru' => 'Хазараспский район',
            ],
            [
                'region_id' => 14,
                'name_uz' => 'Xonqa tumani',
                'name_oz' => 'Хонқа тумани',
                'name_ru' => 'Ханкинский район',
            ],
            [
                'region_id' => 14,
                'name_uz' => 'Xiva tumani',
                'name_oz' => 'Хива тумани',
                'name_ru' => 'Хивинский район',
            ],
            [
                'region_id' => 14,
                'name_uz' => 'Shovot tumani',
                'name_oz' => 'Шовот тумани',
                'name_ru' => 'Шаватский район',
            ],
            [
                'region_id' => 14,
                'name_uz' => 'Yangiariq tumani',
                'name_oz' => 'Янгиариқ тумани',
                'name_ru' => 'Янгиарыкский район',
            ],
            [
                'region_id' => 14,
                'name_uz' => 'Yangibozor tumani',
                'name_oz' => 'Янгибозор тумани',
                'name_ru' => 'Янгибазарский район',
            ],
            [
                'region_id' => 14,
                'name_uz' => 'Urganch',
                'name_oz' => 'Урганч',
                'name_ru' => 'Ургенч',
            ],
            [
                'region_id' => 14,
                'name_uz' => 'Xiva',
                'name_oz' => 'Хива',
                'name_ru' => 'Хива',
            ],
            [
                'region_id' => 14,
                'name_uz' => 'Tuproqqal’a tumani',
                'name_oz' => 'Тупроққалъа тумани',
                'name_ru' => 'Тупроккалинский район',
            ],
            [
                'region_id' => 15,
                'name_uz' => 'Amudaryo tumani',
                'name_oz' => 'Амударё тумани',
                'name_ru' => 'Амударьинский район',
            ],
            [
                'region_id' => 15,
                'name_uz' => 'Beruniy tumani',
                'name_oz' => 'Беруний тумани',
                'name_ru' => 'Берунийский район',
            ],
            [
                'region_id' => 15,
                'name_uz' => 'Qorao\'zak tumani',
                'name_oz' => 'Қораўзак тумани',
                'name_ru' => 'Караузякский район',
            ],
            [
                'region_id' => 15,
                'name_uz' => 'Kegeyli tumani',
                'name_oz' => 'Кегейли тумани',
                'name_ru' => 'Кегейлийский район',
            ],
            [
                'region_id' => 15,
                'name_uz' => 'Qo\'ng\'irot tumani',
                'name_oz' => 'Қўнғирот тумани',
                'name_ru' => 'Кунградский район',
            ],
            [
                'region_id' => 15,
                'name_uz' => 'Qanliko\'l tumani',
                'name_oz' => 'Қанликўл тумани',
                'name_ru' => 'Канлыкульский район',
            ],
            [
                'region_id' => 15,
                'name_uz' => 'Mo\'ynoq tumani',
                'name_oz' => 'Мўйноқ тумани',
                'name_ru' => 'Муйнакский район',
            ],
            [
                'region_id' => 15,
                'name_uz' => 'Nukus tumani',
                'name_oz' => 'Нукус тумани',
                'name_ru' => 'Нукусский район',
            ],
            [
                'region_id' => 15,
                'name_uz' => 'Taxiatosh tumani',
                'name_oz' => 'Тахиатош тумани',
                'name_ru' => 'Тахиаташский район',
            ],
            [
                'region_id' => 15,
                'name_uz' => 'Taxtako\'pir tumani',
                'name_oz' => 'Тахтакўпир тумани',
                'name_ru' => 'Тахтакупырский район',
            ],
            [
                'region_id' => 15,
                'name_uz' => 'To\'rtko\'l tumani',
                'name_oz' => 'Тўрткўл тумани',
                'name_ru' => 'Турткульский район',
            ],
            [
                'region_id' => 15,
                'name_uz' => 'Xo\'jayli tumani',
                'name_oz' => 'Хўжайли тумани',
                'name_ru' => 'Ходжейлийский район',
            ],
            [
                'region_id' => 15,
                'name_uz' => 'Chimboy tumani',
                'name_oz' => 'Чимбой тумани',
                'name_ru' => 'Чимбайский район',
            ],
            [
                'region_id' => 15,
                'name_uz' => 'Shumanay tumani',
                'name_oz' => 'Шуманай тумани',
                'name_ru' => 'Шуманайский район',
            ],
            [
                'region_id' => 15,
                'name_uz' => 'Ellikqal\'a tumani',
                'name_oz' => 'Элликқалъа тумани',
                'name_ru' => 'Элликкалинский район',
            ],
            [
                'region_id' => 15,
                'name_uz' => 'Nukus',
                'name_oz' => 'Нукус',
                'name_ru' => 'Нукус',
            ],
            [
                'region_id' => 15,
                'name_uz' => 'Bo‘zatov tumani',
                'name_oz' => 'Бўзатов тумани',
                'name_ru' => 'Бузатовский район',
            ],
        ];

        foreach ($dates as $item) {
            District::create($item);    
        }
    }
}
